import { StrataProperty, StrataDocCategory, AgentInfo, Lead, AnalyticsEvent } from "./types";

export const DEFAULT_AGENT: AgentInfo = {
  name: "Marcus Vance",
  title: "Principal Realtor & Strata Specialist",
  brokerage: "West Coast Elite Realty",
  email: "marcus@westcoasteliterealty.com",
  phone: "(604) 555-0192",
  bio: "Marcus has over 12 years of experience specializing in Downtown Vancouver and North Shore strata developments. He assists buyers and sellers in navigating complex strata bylaws, depreciation reports, and contingency reserves.",
  photoUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=256&h=256",
  logoUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=128&h=128",
  primaryColor: "indigo-900",
  accentColor: "teal-600"
};

export const INITIAL_PROPERTIES: StrataProperty[] = [
  {
    id: "prop-patina",
    name: "The Patina - Unit 2402",
    address: "1028 Barclay Street, Vancouver, BC V6Z 0B8",
    strataPlan: "BCS3412",
    unitCount: 256,
    bannerImageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800&h=400",
    activeShareUrl: "https://stratashare.ca/share/patina-2402",
    isShared: true,
    passwordProtected: false,
    documentCount: 8,
    viewsCount: 142,
    downloadsCount: 89,
    leadsCount: 14,
    documents: [
      {
        id: "doc-patina-bylaws",
        name: "BCS3412 Strata Bylaws & Rules Consolidated.pdf",
        category: StrataDocCategory.BYLAWS,
        uploadDate: "2026-04-12",
        size: "4.2 MB",
        fileTextSnippet: `DIVISION 1 - PET REGULATIONS & RESTRICTIONS:
An owner, tenant, or occupant must not keep any pets on a strata lot other than:
- Up to two (2) dogs, or two (2) cats, or one of each.
- No dog of a 'vicious breed' is permitted. Vicious breeds include Pitbulls, Rottweilers, and Dobermans, or any cross thereof.
- All dogs must be registered with the Strata Council prior to moving in.
- All pets must escape common areas on a leash or in a suitable carrier at all times.
- Fines for breach of pet rules are $200 per week of ongoing violation.

DIVISION 2 - RENTALS & LEASES:
- As per the BC Strata Property Act changes, rental restriction bylaws are no longer permitted in British Columbia except for short-term accommodation bylaws. 
- Airbnb, VRBO, or any rentals of less than thirty (30) consecutive days are strictly prohibited under Strata Bylaw 14.5.
- Owners found hosting short-term rentals will be fined up to $1,000 per day of violation.

DIVISION 3 - AMENITIES & RECREATIONAL FACILITIES:
- Roof Deck Garden (34th floor) open daily 6:00 AM to 11:00 PM. No glass containers permitted.
- Gym / Fitness Studio (2nd floor) available 24/7.
- Secure underground visitor parking spaces require a digital guest pass generated by the concierge.`
      },
      {
        id: "doc-patina-minutes-2026",
        name: "BCS3412 Annual General Meeting (AGM) Minutes - Oct 2025.pdf",
        category: StrataDocCategory.MINUTES,
        uploadDate: "2025-10-30",
        size: "1.8 MB",
        fileTextSnippet: `MINUTES OF THE ANNUAL GENERAL MEETING (AGM) - BCS3412 STRATA:
- Held on October 15, 2025, at the Hyatt Regency Conference Hall.
- Total voting members present: 168 (in person) and 34 (by proxy).
- PRESIDENT'S REPORT: Discussion of major mechanical issues. The tower chiller system underwent standard overhaul. Elevators 2 and 3 had circuit boards replaced, costing $23,500 extracted from the CRF (Contingency Reserve Fund).
- RESOLUTION 4 (Passed): Resolution to authorize $75,000 drawdown from the Contingency Reserve Fund for exterior masonry sealing and window washing crane repair.
- RECREATION UPDATE: Discussion of upgrade to gym gear. Council approved $12,000 from current operating budget to replace three spinning cycles and add yoga equipment.`
      },
      {
        id: "doc-patina-depreciation",
        name: "BCS3412 Depreciation Report Consolidated (WSP 2024).pdf",
        category: StrataDocCategory.DEPRECIATION,
        uploadDate: "2024-06-15",
        size: "14.5 MB",
        fileTextSnippet: `EXECUTIVE SUMMARY OF SYSTEM CONDITION AND DEPRECIATION:
- Prepared by WSP Engineering Ltd., June 2024.
- LIFE CYCLES OF MAJOR COMPONENTS:
  1. Roof Membrane: Current 2-ply torch-on membrane was installed in 2018 (Expected life: 20-25 years). Condition: Good. Estimated replacement year: 2038-2040. Cost estimate: $340,000.
  2. Exterior Glazing & Sealing: Window sealants expect overhaul in Year 15-20 (approx 2028-2032). Expected project cost of $250,000.
  3. Plumbing / Piping System: Building utilizes high-grade copper piping. No current indicators of pinhole leaks. Domestic booster pumps were serviced in 2023. Life expectance: 8 more years.
  4. Elevator Modernization: Projected for 2041. Massive cost anticipated of $1.2M. Recommend steady annual contributions to CRF of at least $150,000 specifically allocated logic for high-speed elevators.`
      },
      {
        id: "doc-patina-formb",
        name: "Form B Information Certificate - Unit 2402 - Signed.pdf",
        category: StrataDocCategory.FORM_B,
        uploadDate: "2026-05-18",
        size: "2.1 MB",
        fileTextSnippet: `FORM B INFORMATION CERTIFICATE (Section 59, Strata Property Act):
- Property Reference: Strata Lot 194, BCS3412, Unit 2402.
- Monthly Strata Fee: $648.50 (Due on the 1st of each month). Includes hot water, gas, gas-range maintenance, concierge, gardening, building insurance, garbage removal, and gym access.
- CONTINGENCY RESERVE FUND (CRF) BALANCE:
  - Total CRF Balance as of March 31, 2026: $1,425,000.
  - This exceeds the BC legal guidelines and represents a very healthy reserve.
- SPECIAL ASSESSMENTS:
  - There are currently no active special assessments approved by the Strata Corporation.
  - No pending resolutions for special assessments are listed for the next SGM.
- SPECIAL RULES OR OUTSTANDING LEVY:
  - Strata Lot 194 does not owe any outstanding fees or fines.
  - Parking Stall: Number P2-89 (Assigned under long-term exclusive lease).
  - Storage Locker: Number S-204 (Located in secure locked room P1-B).`
      },
      {
        id: "doc-patina-financials",
        name: "BCS3412 Financial Statement - Dec 2025 (Audited).pdf",
        category: StrataDocCategory.FINANCIALS,
        uploadDate: "2026-02-10",
        size: "3.5 MB",
        fileTextSnippet: `BCS3412 ANNUAL REVENUE AND EXPENDITURES (Audited by KPMG, Year Ended Dev 31, 2025):
- Operating Income: $1,980,000
- Operating Expenses: $1,750,000
- Surplus transferred to CRF: $230,000
- Major cost centers:
  - Utilities (Electricity & Water): $410,000
  - Concierge & Janitorial Contract: $340,000
  - Landscaping & Snow Removal: $45,000
  - Insurance Premium: $375,000 (Noticeable 8% increase compared to 2024 due to global insurance hardening, but no risk of deductible hikes).`
      },
      {
        id: "doc-patina-insurance",
        name: "Strata BCS3412 Insurance Certificate 2026-2027.pdf",
        category: StrataDocCategory.OTHER,
        uploadDate: "2026-03-01",
        size: "1.1 MB",
        fileTextSnippet: `CERTIFICATE OF DIRECT INSURANCE - STRATA PLAN BCS3412:
- Broker: BFL Canada Insurance Services Inc.
- Policy Period: March 1, 2026, to March 1, 2027.
- INSURED LIMITS:
  - All Risks Property: $148,000,000
  - Earthquake coverage: Included (20% deductible rate)
  - Flood Cover: $15,000,000 ($50,000 deductible)
  - Water Damage Deductible: $100,000 per claim. (Note to owners: It is highly recommended that you obtain personal condominium insurance with water deductible coverage of $100,000 to cover potential backflows caused by washing machines or overflows).
  - Commercial General Liability: $20,000,000`
      },
      {
        id: "doc-patina-minutes-feb26",
        name: "BCS3412 Strata Council Minutes - February 2026.pdf",
        category: StrataDocCategory.MINUTES,
        uploadDate: "2026-02-20",
        size: "1.4 MB",
        fileTextSnippet: `STRATA COUNCIL MEETING MINUTES - BCS3412:
- Held in Amenity Lounge, February 10, 2026, at 7:00 PM.
- Discussions on leak reporting in Unit 408: Plumber called immediately, leak was tracked to owner's internal washing machine hose. Fines under investigation for slow containment.
- EV charging project: council is preparing a budget proposal for AGM to retrofit 40 more parking stalls in P3 with Level 2 chargers. Application submitted to BC Hydro for rebate program.`
      },
      {
        id: "doc-patina-plan",
        name: "Strata Plan BCS3412 Registered Site Layout.pdf",
        category: StrataDocCategory.OTHER,
        uploadDate: "2026-05-02",
        size: "5.8 MB",
        fileTextSnippet: `REGISTERED STRATA PLAN BCS3412 - SITE LAND PLAN:
- Surveyed by McElhanney land drafting team.
- Shows all 34 structural levels, parking grids, and access corridors.
- Unit 2402 is registered as Strata Lot 194, corner northwest-facing orientation. Gross registered internal area: 981 sq ft, plus balustrade balcony area of 74 sq ft. Exclusive entitlement of walls and common plumbing.`
      }
    ],
    agentInfo: DEFAULT_AGENT
  },
  {
    id: "prop-shangri-la",
    name: "Shangri-La Residences - Unit 3903",
    address: "1128 West Georgia Street, Vancouver, BC V6E 0A8",
    strataPlan: "BCS2910",
    unitCount: 320,
    bannerImageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=800&h=400",
    activeShareUrl: "https://stratashare.ca/share/shangrila-3903",
    isShared: true,
    passwordProtected: true,
    accessPassword: "shangrila-elite",
    documentCount: 5,
    viewsCount: 215,
    downloadsCount: 124,
    leadsCount: 31,
    documents: [
      {
        id: "doc-shangrila-bylaws",
        name: "BCS2910 Strata Bylaws Consolidated.pdf",
        category: StrataDocCategory.BYLAWS,
        uploadDate: "2026-01-05",
        size: "5.1 MB",
        fileTextSnippet: `PET RESTRICTIONS:
- Only one (1) dog or one (1) cat per strata lot is allowed. Maximum weight of the animal must not exceed 15 kg (approx 33 lbs) when fully grown.
- Proper registration with the Front Desk concierge is mandatory.
- Pets must not be allowed loose anywhere on the shared pathways and must be carried in arms inside elevators or hotel lobby common walk paths.

SHORT TERM RENTALS:
- Short term occupancy is strictly prohibited. Minimally 1-year tenancy required. Any breach is subject to a $500 penalty per occurrence.`
      },
      {
        id: "doc-shangrila-formb",
        name: "Form B Info Certificate - Dec 2025.pdf",
        category: StrataDocCategory.FORM_B,
        uploadDate: "2025-12-15",
        size: "1.9 MB",
        fileTextSnippet: `FORM B CERTIFICATE - STRATA LOT 88, BCS2910, UNIT 3903.
- Monthly Strata fee: $912.40.
- Includes: Geothermal heating & cooling, 24/7 valet concierge, pool & spa, hot water, building insurance, secure parking slot P3-12.
- Contingency Reserve Fund (CRF) Balance: $2,840,000. Excellent financial health.
- Special Assessments: None.
- Outstanding levies or fines against Unit 3903: None.`
      },
      {
        id: "doc-shangrila-rep",
        name: "Shangri-La BCS2910 Depreciation Audit.pdf",
        category: StrataDocCategory.DEPRECIATION,
        uploadDate: "2024-11-20",
        size: "11.2 MB",
        fileTextSnippet: `SHANGRI-LA STRUCTURAL CONDITIONS REPORT (2024):
- Geothermal exchange loops flushed and calibrated in October 2024. Expected performance rating is excellent.
- High-rise glazing structural sealant checks done. Minor caulking deterioration on levels 42-45 was replaced.
- Glass panels on balconies passed modern safety testing.`
      },
      {
        id: "doc-shangrila-minutes",
        name: "BCS2910 AGM Minutes - February 2026.pdf",
        category: StrataDocCategory.MINUTES,
        uploadDate: "2026-03-10",
        size: "2.4 MB",
        fileTextSnippet: `AGM MINUTES - HELD MARCH 4, 2026:
- Approved the 2026 operating budget with a reasonable 4% allowance for inflation adjustments.
- Discussed pool tile refurbishment project. Contract signed with Wet-Tech Pools for $45,000, funded fully from CRF surplus.`
      },
      {
        id: "doc-shangrila-insurance",
        name: "Strata Insurance Binder - BCS2910 (Current).pdf",
        category: StrataDocCategory.OTHER,
        uploadDate: "2026-05-01",
        size: "1.2 MB",
        fileTextSnippet: `STRATA DIRECT PROPERTY INSURANCE POLICY:
- Insured with Lloyd's Syndicates and Intact Insurance.
- Water damage limit: $150,000 deductible.
- Earthquake deductible rate: 15% overall.`
      }
    ],
    agentInfo: DEFAULT_AGENT
  }
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    propertyId: "prop-patina",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@gmail.com",
    phone: "(604) 555-4423",
    purpose: "buyer",
    date: "2026-06-03T14:24:00Z",
    downloadedDocs: [
      "BCS3412 Strata Bylaws & Rules Consolidated.pdf",
      "Form B Information Certificate - Unit 2402 - Signed.pdf"
    ]
  },
  {
    id: "lead-2",
    propertyId: "prop-patina",
    name: "David Kim",
    email: "david@kimassociates.ca",
    phone: "(778) 555-8912",
    purpose: "buyer_agent",
    date: "2026-06-05T09:12:00Z",
    downloadedDocs: [
      "BCS3412 Strata Bylaws & Rules Consolidated.pdf",
      "BCS3412 Annual General Meeting (AGM) Minutes - Oct 2025.pdf",
      "BCS3412 Depreciation Report Consolidated (WSP 2024).pdf"
    ]
  },
  {
    id: "lead-3",
    propertyId: "prop-shangri-la",
    name: "Emily Chen",
    email: "emily_c@chicagotech.co",
    phone: "(416) 555-9081",
    purpose: "buyer",
    date: "2026-06-06T18:35:00Z",
    downloadedDocs: [
      "BCS2910 Strata Bylaws Consolidated.pdf",
      "Form B Info Certificate - Dec 2025.pdf"
    ]
  }
];

export const MOCK_ANALYTICS: AnalyticsEvent[] = [
  {
    id: "event-1",
    propertyId: "prop-patina",
    eventType: "view",
    details: "Visitor viewed Patina share landing page from Chrome / macOS",
    timestamp: "2026-06-07T02:14:00Z"
  },
  {
    id: "event-2",
    propertyId: "prop-patina",
    eventType: "lead_register",
    details: "Sarah Jenkins registered to download documents",
    timestamp: "2026-06-03T14:24:00Z"
  },
  {
    id: "event-3",
    propertyId: "prop-patina",
    eventType: "download_zip",
    details: "Sarah Jenkins downloaded all BCS3412 documents as a ZIP",
    timestamp: "2026-06-03T14:25:12Z"
  },
  {
    id: "event-4",
    propertyId: "prop-shangri-la",
    eventType: "view",
    details: "Visitor opened Shangri-La share landing page",
    timestamp: "2026-06-07T05:40:00Z"
  },
  {
    id: "event-5",
    propertyId: "prop-shangri-la",
    eventType: "lead_register",
    details: "Emily Chen registered to view password-protected files",
    timestamp: "2026-06-06T18:35:00Z"
  }
];

export const FAQS = [
  {
    question: "What are 'strata documents' in British Columbia?",
    answer: "In BC, when buying a strata property (like a condo, townhouse, or duplex), the Buyer is legally entitled to undergo due diligence. Strata documents include the strata plan, current bylaws and regulations, at least two years of General Meeting (AGM/SGM) and monthly council minutes, a Form B Information Certificate, recent budgets, insurance coverage binders, and a professional Depreciation Report."
  },
  {
    question: "How does Strata Share help real estate listing agents?",
    answer: "Instead of emailing bulky, disorganized PDF attachments to separate buying agents or manually saving them on personal Dropbox folders, Strata Share allows listing agents to upload all strata files to a central, elegant, branded landing page. When a co-operating brokerage or prospective buyer wants access, they register their contact information. This automates lead capture and ensures documents are delivered perfectly."
  },
  {
    question: "What is 'Branded Strata PDF Sharing'?",
    answer: "Every strata share link has your specific Realtor name, title, profile picture, brokerage banner, and contact coordinates at the top of the folder. When a prospective client or another broker reads or downloads files, you stay top-of-mind, showcasing your professional digital marketing."
  },
  {
    question: "Can I password-protect sensitive strata documents?",
    answer: "Yes. In BC, Strata Plans and Bylaws are publicly accessible, but Minutes, Financials, and Form Bs may contain sensitive building details. You can easily enable password protection on a per-property share level, requiring buyers to input a passcode (or request it from you) to unlock files."
  },
  {
    question: "How does the AI Strata Review Copilot work?",
    answer: "Strata Share integrates a secure, modern Gemini AI engine on the server. Buyers, realtors, or lenders can select any document (such as a 120-page Bylaw file) and ask questions in plain English (e.g., 'Are there pet weight limits?' or 'Is there a balcony refurb assessment?'). The AI scans the document's verified text, extracts key clauses, and provides precise summaries instantly, saving hours of manual parsing."
  },
  {
    question: "Is there an easy way for buyers to download everything?",
    answer: "Yes, our landing page includes an 'Instant ZIP compiler' that gathers all currently uploaded documents and packages them into a single, labeled zip file in one click."
  }
];
